# Generated by Django 3.2.3 on 2021-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='second_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
