# Generated by Django 3.2.3 on 2021-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210528_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
